#!/bin/bash
#
# These programs must run continuously throughout the session.
# It may be necessary to manage them by hand (see also the Makefile).
#   $1 = start | stop | restart | status
#   $2 = compton | marks | commands
# The compositor (compton) doesn't make a window. It must be disabled
# whenever the xubuntu software updater runs, lest the latter becomes
# invisible (shaded)!
#


case "$1" in
    (start)
        case "$2" in
            (compton)
                compton -b --config "${HOME}/.config/compton.conf"
                ;;
            (marks)
                (xfce4-terminal -T "$(date +%T) marks" \
                                -x "${HOME}/local/bin/i3-marks" update) &
                i3-marks numeric
                ;;
            (commands)
                (xfce4-terminal -T "$(date +%T) commands" \
                                -x "${HOME}/local/bin/i3-file-watcher") &
                i3-marks numeric
                ;;
        esac
        ;;
    (stop)
        case "$2" in
            (compton)
                # start|stop strings must be identical.
                pkill -f "compton -b --config ${HOME}/.config/compton.conf"
                ;;
            (marks)
                # This kills everything shown in status.
                [ "$(pgrep -c -f i3-marks)" -gt 0 ] && killall i3-marks
                ;;
            (commands)
                #
                cmd="--watch-files /dev/shm/$USER/i3/command"
                exe="--on-modify-command /dev/shm/$USER/i3/execute"
                pkill -f "perl /usr/bin/inotify-hookable ${cmd} ${exe}"
                ;;
        esac
        ;;
    (status)
        case "$2" in
            (compton)
                pgrep -a -f "$2" | grep -v grep | grep -v "$(basename "$0")"
                ;;
            (marks)
                # Expect 3 pids, contiguously numbered, but not shown
                # in order, when not stopped.
                pgrep -a -f 'i3-msg -t subscribe -m' | grep window
                pgrep -a -f 'i3-marks update'
                ;;
            (commands)
                # Expect 2 pids.
                pgrep -a -f '/usr/bin/inotify-hookable'
                pgrep -a -f 'i3-file-watcher'
                ;;
            (all)
                #
                for option in compton marks commands; do
                    printf "%s:\n%s\n" ${option} "$($0 status $option)"
                done
                ;;
        esac
        ;;
    (restart)
        # 2021-02-24: Shutdown both services before restarting the WM,
        # allow time for WM restart, then restart both services.  The
        # workspace for the terminal windows is renamed by setting $2
        # to the old name and $3 to the new name. Omitting $3 uses $2
        # as the workspace name. Omitting $2 sets the workspace name
        # to the default "wm" and starts both services (for use with
        # i3-config on first run of the session).
        if [ "_$2" = "_" ]; then
            i3-msg "workspace wm"
        else
            $0 stop commands
            $0 stop marks
            i3-msg "[workspace=\"${3:-$2}\"] kill"
            sleep 3
            i3-msg "restart"
            sleep 5
            i3-msg "workspace \"$2\""
        fi
        sleep 2
        $0 start commands
        $0 start marks
        ;;
esac

#
# Done,
#
