#!/bin/bash
#
# i3-command-prompt.
#

# The "Command Interface" file is frequently modified.
dir="/dev/shm/${USER}/i3"
file="command"


#
# Pass the command entered into the dmenu command prompt into the
# command interface.
#
menu()
{
    # In order to reduce manual keystrokes, the Return key is pressed
    # automatically after the timeout expires.
    commandtimeout=${2:-5}
    ( sleep "${commandtimeout}" && \
          [ "$(pgrep -c -f 'dmenu -b -m 0 -fn pango:DejaVu Sans 11 -p Command: ')" -gt 0 ] && \
          xdotool key Return
    ) &  # Explicit  subshell.
    numlockx on
    # This is the stub of a menu because the timeout doesn't allow
    # enough time to navigate.  Spaces are mapped to linefeeds.
    cmd=$(echo "cancel" | sed 's/\ /\n/g' | \
                 dmenu -b -m 0 -fn 'pango:DejaVu Sans 11' -p 'Command: ')
    if [ "${cmd}" = "cancel" ]; then
        numlockx off
    else
        numlockx off
        echo "${cmd}" > "${dir}/${file}"
    fi
}

#
# Pass the specified command directly into the command interface.
#
nomenu()
{
    echo "$1" > "${dir}/${file}"
}

#
# Start here.
#

case "$1" in
    (menu)
        "$1" "$2"  # $2 is the timeout.
        ;;
    (nomenu)
        "$1" "$2" # $2 is the command.
        ;;
esac
#
# Done.
#
