#!/bin/bash
#
# i3-dispatcher
#

# Forward a command or command alias or indeed anything with a
# recognisable header to a handler function.
#
forward ()
{
    export PATH=${HOME}/local/bin:${PATH}
    case "$1" in
	([a-z][0-9])
	    nohup i3-focus-app-by-alias focus "$1"
	    ;;
	([a-z][a-z])
	    nohup i3-focus-app-by-alias focus "$1"
            ;;
        (0000)
            nohup i3-transcribe clipboard "${@:2}"
            ;;
        (0001)
            nohup i3-transcribe editor "${@:2}"
            ;;
        ([1][0-9][0-9][0-9])
            nohup i3-launcher start "$1" "$2" "${@:3}"
	    ;;
        ([2][0][0-9][0-9])
            nohup i3-launcher stop_oldest "$1" "$2" "${@:3}"
            ;;
        ([2][1][0-9][0-9])
            nohup i3-launcher stop_handle "$1" "$2" "${@:3}"
            ;;
	([1-9][0-9][0-9])
	    nohup i3-triple-digit-command "$1"
	    ;;
	([0-9][0-9])
	    nohup i3-double-digit-command "$1"
	    ;;
	(*)
	nomatchfound "$*"
	    ;;
    esac
}

# Error message handler.
nomatchfound ()
{
    # This message delivery is non-blocking.
    (echo "i3-dispatcher: No match found! \"$*\"" |
	 dmenu -b -fn "pango:DejaVu Sans 11") &
    sleep "$2"
    # This key event effects a timeout, but only if the user
    # hasn't dismissed the dmenu first. It isn't watertight.
    if [ "$(pgrep -c -af 'dmenu -b -fn pango:DejaVu Sans 11')" -eq 1 ]; then
	xdotool key --clearmodifiers  Escape
    fi
}

#
# Start here.
#

# (1) "forward"
# (2) 1000 ... 9999
# (3) mpv <stream>
#

"$1" "$2" "${@:3}"

#
## Done.
#]
