#!/bin/bash
#
# i3-dispatcher
#

#
# Forward the command to a dedicated function.
#
forward ()
{
    export PATH=${HOME}/local/bin:${PATH}
    case "$1" in
	([a-z][0-9])
            # Sent from command prompt.
	    nohup i3-focus-app-by-alias focus "$1"
	    ;;
	([a-z][a-z])
            # Sent from command prompt.
	    nohup i3-focus-app-by-alias focus "$1"
            ;;
        (clip|edit)
            # Sent from Tasker & AutoVoice.
            nohup i3-transcribe "${@}"
            ;;
        (start|stop)
            # Sent from Tasker & TVH plugin.
            nohup i3-launcher "${@}"
            ;;
        (interrupt)
            # I use this to overlay each of my screens with a specific
            # image when my phone is ringing. The user should supply
            # the code to be executed on the target inside Tasker.
            eval "${*:2}"
            ;;
	(*)
            notify-send "no match found >$*<"
	    ;;
    esac
}


#
# Start here.
#

# Debug.
notify-send -t 10000 "$(cat /dev/shm/"$USER"/i3/command)"

# "forward" $2 $3 ...
"${@}"

#
# Done.
#
