#!/bin/bash
#
# i3-double-digit-command
#

# RESERVED. Functionality moved into triple-digit-command file. If we
# add another file, editing the Makefile is faciltated by search and
# replace.

#
# Start here.
#

/bin/true

#
# Done.
#
