#!/bin/bash
#
# i3-dispatcher
#

#
# Forward the command to a dedicated function.
#
forward ()
{
    # DANGER WILL ROBINSON! Do not "tidy up" (= "delete") this line:
    export PATH=${HOME}/local/i3/bin:${PATH}
    case "$1" in
        ([0-9][0-9][0-9])
            # Sent from numpad command prompt. The numpad layout is
            # allegedly faster than the Menu key command prompt due
            # to the numbers being close together.
            nohup "${HOME}"/local/i3/bin/i3-triple-digit-command "$1"
            ;;
        ([0-9][0-9])
            # Sent from numpad command prompt.
            # "triple" is not a typo here.
            nohup "${HOME}"/local/i3/bin/i3-triple-digit-command "$1"
            ;;
	([a-z][0-9])
            # Sent from command prompt.
	    nohup "${HOME}"/local/i3/bin/i3-focus-app-by-alias focus "$1"
	    ;;
	([a-z][a-z])
            # Sent from command prompt.
	    nohup "${HOME}"/local/i3/bin/i3-focus-app-by-alias focus "$1"
            ;;
        (clip|edit)
            # Sent from Tasker & AutoVoice.
            nohup "${HOME}"/local/i3/bin/i3-transcribe "${@}"
            ;;
        (interrupt)
            # I use this to overlay each of my screens with a specific
            # image when my phone is ringing. The user should supply
            # the code to be executed on the target inside Tasker.
            eval "${*:2}"
            ;;
	(*)
            notify-send "i3-dispatcher:" \
                        "Command not found: &lt;$*&gt; request rejected."
	    ;;
    esac
}


#
# Start here.
#


forward "${@:2}"

#
# Done.
#
