#!/bin/bash
#
# Writing to the $i3/command file causes the $i3/execute file to
# evaluate the contents of the $i3/command file.
#

#
# Start here.
#

# Create the directory and files. Set the strictest permissions.
i3=/dev/shm/$USER/i3
mkdir -p "${i3}"
touch "$i3/command"
chmod 600 "$i3/command"
touch "$i3/execute"
chmod 700 "$i3/execute"

# Set the file contents. The command is initialised with a nop.  The
# execute command has to be expanded at dispatch time.  Single quotes
# ensure that the string is not expanded when copied into the execute
# file. Shellcheck doesn't think this is what we want so the warning
# is disabled. Note: "echo" joins its string arguments with a space.

# shellcheck disable=SC2016
echo 'eval /bin/false' > "${i3}/command"
# shellcheck disable=SC2016
echo 'eval $HOME/local/bin/i3-dispatcher forward' \
     '$(cat /dev/shm/$USER/i3/command)' > "${i3}/execute"
# Be careful! Use no terminal here! Use no ampersand here!
inotify-hookable --watch-files "${i3}"/command --on-modify-command "${i3}"/execute

#
# Done.
#
