#!/bin/bash
#
# i3-launcher
#

#
# 2020-05-27 : The fake/real PID idea became baroque. Apply KISS for
# release.
#

#
# Launch a program and register it.
#
start ()
{
    if [ "${2:0:1}" = "/" ]; then
        # Absolute paths can be detected reliably.
        # Allowing arbitrary programs is insecure.
        app="mpv"
        i3-msg "exec --no-startup-id ${app} ${*:2}"
    else
        app=$2
        i3-msg "exec --no-startup-id ${*:2}"
    fi
}

#
# Kill a program and deregister it.
#
stop ()
{
    echo "STOP"
    pkill --oldest -f mpv
}

#
# Start here.
#

if [ $# -ne 1 ]
then
    # shellcheck disable=SC2068
    eval start "$1" ${@:2}
else
    eval stop "$1"
fi



#
# Done.
#
