#!/bin/bash
#
# i3-launcher
#

#
# 2020-05-27 : The fake/real PID idea became baroque. Apply KISS for
# release.
#

#
# Launch a program and register it.
#
# (1) four digit handle (reserved, unused).
# (2) mpv, vlc, ...
# (.) stream
#
start ()
{
    if [ "${2:0:1}" = "/" ]; then
        # Absolute paths can be detected reliably.
        # Allowing arbitrary programs is insecure.
        app="mpv"
        i3-msg "exec --no-startup-id ${app} ${*:2}"
    else
        app=$2
        i3-msg "exec --no-startup-id ${*:2}"
    fi
}

#
# Kill a program and deregister it.
#
# (1) four digit handle (reserved, unused).
# (2) mpv, vlc, ...
# (.) streaam
#
stop ()
{
    if [ "${2:0:1}" = "/" ]; then
        pid="$(pgrep --oldest -f "mpv")"
    else
        pid="$(pgrep --oldest -f "$2")"
    fi
    kill $((pid + 1)) "${pid}"
}

#
# Start here.
#

# (1) start|stop
# (2) four digit handle
# (3) mpv, vlc, ...
# (.) streaam

case "$1" in
    (start)
        eval start "$2" "$3" "${@:4}"
        ;;
    (stop)
        eval stop "$2" "$3" "${@:4}"
        ;;
esac

#
# Done.
#
