#!/bin/bash
#

#
# Assign a 2 digit mark to a window.
#
numeric()
{
    # Generate a random 2 digit mark.  Reject and retry if it matches
    # an assigned mark. The retry loop takes more time as the number
    # of marked containers approaches 100.
    while : ; do
        id=$((10#$(date +%N) % 100))
        id=$(printf "%02d" "${id}")
        count=$(for m in $(i3-msg -t get_marks | grep '[0-9][0-9]' | sed 's/,/\ /g');
                do echo "${m}"; done | grep -c "${id}")
        if [ "${count}" -eq 0 ]; then break; fi
    done
    sleep 1 # No need for caller to wait for the window.
    windowid=$(printf "0x%x" "$(xdotool getwindowfocus)")
    i3-msg "[id=\"${windowid}\"] mark --toggle \"${id}\""
    i3-msg "[con_mark=\"${id}\"] focus"
}

#
# Mark the focused window with the workspace name defined by the
# command alias.
#
# - Note: These marks could and should be hidden by prefixing with an
# - underscore. They are exposed for debug and test convenience only.
#
commandalias()
{
    cws=$(i3-msg -t get_workspaces | jq '.[] | .name,.focused' | \
              grep true -B1 | grep -v true)
    windowid=$(printf "0x%x" "$(xdotool getwindowfocus)")
    # Fetch all the workspace marks in a list and walk that list,
    # removing any matching mark on the current window. This ugly
    # "brute force and ignorance" method needs improvement.
    for mark in $(i3-msg -t get_marks | \
                      sed 's/"[0-9][0-9]"//g' | sed 's/,/ /g'| sed 's/[][]//g')
    do
        i3-msg "[id=\"${windowid}\"] unmark ${mark}"
    done
    # Apply the workspace mark without changing the numeric mark.
    i3-msg "[id=\"${windowid}\"] mark --add --replace ${cws}"

    # Having set up a window subscription and a listener for updating
    # marks, add another listener to the linked list.
    (floating) &
}

#
# If a workspace is empty and a terminal is launched from there, the
# terminal will be made floating, but should any other window appear,
# it will be tiled.
#
floating()
{
    # 4 years ago /u/airblader wrote the code to return the
    # identifiers of the windows on the current workspace.
    count=$(for w in $(xdotool search --all --onlyvisible --desktop \
                       "$(xprop -notype -root _NET_CURRENT_DESKTOP | \
                                               cut -c 24-)" "" 2>/dev/null) ; do
                # EllaTheCat wrapped that in a for-loop to count the
                # identifiers.
                xdotool getwindowname "$w"; done | wc -l)

    case "${count}" in
        (1)
            # Forced floating should be specific, hence the command
            # criteria ("cc") mention xfce4-terminal.
            cc="[workspace=\"__focused__\" instance=\"xfce4-terminal\"]"
            cmds="floating enable, resize set 60 ppt 60 ppt, move position center;"
            i3-msg "$(printf "%s %s" "${cc}" "${cmds}")"
            ;;
        (2)
            i3-msg "[workspace=\"__focused__\"] floating disable;"
            ;;
    esac
}


#
# When the monitor indicates a window change, walk the "linked list"
# with "commandalias" at the head.
#
update()
{
    # shellcheck disable=SC2034
    i3-msg -t subscribe -m '[ "window" ]' | \
        while read -r line ; do commandalias; read -r line; read -r line; done
}


#
# Start here.
#

case "_$1" in
    (_numeric)
        numeric
        ;;
    (_commandalias)
        commandalias
        ;;
    (_floating)
        floating
        ;;
    (_update)
        update
        ;;
esac

#
# Done.
#
