#!/bin/bash
#

#
# Assign a 2 digit mark to a window.
#
numeric()
{
    # Generate a random 2 digit mark.  Reject and retry if it matches
    # an assigned mark. The retry loop takes more time as the number
    # of marked containers approaches 100.
    while : ; do
        id=$((10#$(date +%N) % 100))
        id=$(printf "%02d" "${id}")
        count=$(for m in $(i3-msg -t get_marks | grep '[0-9][0-9]' | sed 's/,/\ /g');
                do echo "${m}"; done | grep -c "${id}")
        if [ "${count}" -eq 0 ]; then break; fi
    done
    sleep 1 # No need for caller to wait for the window.
    windowid=$(printf "0x%x" "$(xdotool getwindowfocus)")
    i3-msg "[id=\"${windowid}\"] mark --toggle \"${id}\""
    i3-msg "[con_mark=\"${id}\"] focus"
}

#
# Mark the focused window with the workspace name defined by the
# command alias.
#
# - Note: These marks could and should be hidden by prefixing with an
# - underscore. They are exposed for debug and test convenience only.
#
commandalias()
{
    cws=$(i3-msg -t get_workspaces | jq '.[] | .name,.focused' | \
              grep true -B1 | grep -v true)
    windowid=$(printf "0x%x" "$(xdotool getwindowfocus)")
    # Fetch all the workspace marks in a list and walk that list,
    # removing any matching mark on the current window. This ugly
    # "brute force and ignorance" method needs improvement.
    for mark in $(i3-msg -t get_marks | \
                      sed 's/"[0-9][0-9]"//g' | sed 's/,/ /g'| sed 's/[][]//g')
    do
        i3-msg "[id=\"${windowid}\"] unmark ${mark}"
    done
    # Apply the workspace mark without changing the numeric mark.
    i3-msg "[id=\"${windowid}\"] mark --add --replace ${cws}"
}

#
# When the monitor indicates a window change, update the marks.
#
update()
{
    # This is simple and reliable but myopic.
    pkill -f "i3-msg -t subscribe"
    # shellcheck disable=SC2034
    i3-msg -t subscribe -m '[ "window" ]' | \
        while read -r line ; do commandalias; read -r line; read -r line; done
}


#
# Start here.
#

case "_$1" in
    (_numeric)
        numeric
        ;;
    (_commandalias)
        commandalias
        ;;
    (_update)
        update
        ;;
esac

#
# Done.
#
