#!/bin/bash
#
# Objective: This module captures desktop video and audio. Clips can
# then be aggregated to make a demo video in the style of YouTube.
#
# References: (1) https://unix.stackexchange.com/a/117623
#


xy=+1920+0   ### top left corner of the region, i.e anchot
wh=1920x1080 ### region occupying the entire screen of the current monitor.

pass1dir=/dev/shm/$USER/i3/video/
pass1dir=${HOME}/Videos/
pass2dir=${HOME}/Videos/
pass1file=grab.mkv
pass2file=grab.mp4

#
# 2 pass recording: pass 1 lossless capture, pass 2 encoding
#
record()
{
    case "$1 $2" in
        (video?start)
            rm -f "${pass1dir}/${pass1file}"
            (ffmpeg \
                 -f pulse -ac 2 -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor \
                 -f x11grab -s ${wh} -r 25 -i :0.0${xy} -c:v huffyuv \
                 -q:v 0 -y "${pass1dir}/${pass1file}") &
            ;;
        (video?stop)
            pkill -f "ffmpeg"
            ffmpeg -i "${pass1dir}/${pass1file}" -c:v mpeg4 -c:a mp3 \
                   -q:v 0 -y "${pass2dir}/${pass2file}"
            ;;
        (video?[1-9][0-9]|video?[1-5][0-9][0-9])
            record 'video' 'start'
            sleep "$2"
            record 'video' 'stop'
            ;;
        (*)
            echo "record: video command argument: $2 not supported"
            exit 1
            ;;
    esac
}


#
# Start here.
#

mkdir -p "${pass1dir}" "${pass2dir}"

record "$1" "$2"

#
# Done.
#
