#!/bin/bash
#
# i3-scratchpad
#

#  Constants copied from i3-config must maintain consistency.

###export lmon="HDMI-2"
export cmon="HDMI-1"
###export rmon="HDMI-1"

#
# Toggle the scratchpad terminal between show and hide.
#
toggle_terminal()
{
    # Only one key binding is required, the first keypress performs
    # initialisation and hides the terminal again.
    if [ "_$(xdotool search --classname "Scratchpad" | head -1)"  = "_" ]; then
        xfce4-terminal --title=Scratchpad &
	# Allow the terminal enough time to initialise.
	# This value needs to be "just right", ymmv.
        sleep 0.3
        # Set the instance to identify the scratchpad.
        xdotool getwindowfocus set_window --classname "Scratchpad"
        compton-trans -c -o 88
        i3-msg "[instance=\"Scratchpad\"] resize set 80 ppt 80 ppt"
        i3-msg "[instance=\"Scratchpad\"] move position center"
        i3-msg "[instance=\"Scratchpad\"] move scratchpad"
    else
        # Remove any accumulated workspace marks before showing the
        # window. Numeric marks are removed as a side effect.
        i3-msg "[instance=\"Scratchpad\"] unmark, scratchpad show;"
    fi
}

#
# Start here.
#

"$1"

#
# Done.
#
