#!/bin/bash
#
# i3-double-digit-command
#

# Copy from i3-config, paste and edit to be bash environment variables.
export analogaudiosink=alsa_output.pci-0000_00_1b.0.analog-stereo
export bluetoothaudiosink=bluez_sink.00_01_01_00_12_CB
export hdmiaudiosink=alsa_output.pci-0000_00_03.0.hdmi-stereo
usbaudiosink=alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo

# Reverse engineered. >wave arms and mumble<
usbaudiocard=alsa_card.usb-C-Media_Electronics_Inc._USB_Audio_Device-00
usbaudioport=analog-output-speaker

#
# - Manage containers with marks.
# - Manage USB audio volumes.
# - Manage USB audio latency.
#
i3_triple_digit()
{
    case "$1" in
        ([1][0-9][0-9])
            # Audio latency offset. The two digits are interpreted as
            # a percentage of one second.
            arg="${1:1:2}"
            arg=$((arg * 10000))
            pactl set-port-latency-offset \
                  ${usbaudiocard} ${usbaudioport} ${arg}
            ;;
        ([2][0-9][0-9])
            # Volume settings 00 to 99. Although pavucontrol allows as
            # high as 150% the API doesn't.
            arg="${1:1:2}"  # USB volume as a percentage.
            pactl set-sink-volume ${usbaudiosink} "${arg}0000"
            ;;
        ([[4]0-9][0-9])
            # Visit a two-digit mark using numpad or voice.
            arg="${1:1:2}"
            i3-msg "[con_mark=\"${arg}\"] focus"
            ;;
         ([5][0-9][0-9])
            # Swap this container with the matching marked container.
            arg="${1:1:2}"
            i3-msg "swap container with mark ${arg}"
            ;;
         ([036789][0-9][0-9])
             # Define all other 3 digit matches.
             arg="${1:1:2}"
             notify-send "undefined 3 digit command alias >${arg}< acknowledged."
             ;;
         ([0-9][0-9])
             # Available 2 digit matches.
             arg="${1:0:2}"
             notify-send "undefined 2 digit command alias >${arg}< acknowledged."
             ;;
   esac
}

#
# Start here.
#

i3_triple_digit "$1"

#
# Done.
#
