#!/bin/bash
#
# Arrange the dual displays for my raspberry pi 4.
#
# - The utility that comes with Raspbian shows two rectangles. The
# - "same-as" layout can be achieved by dragging one on top of the
# - other, the order is important.
#

case "$(hostname)" in
    (cheesecake)
        case "${1:-same}" in
            (left*)
                xrandr --output HDMI2 --left-of HDMI1
                ;;
            (right*)
                xrandr --output HDMI2 --right-of HDMI1
                ;;
            (same*)
                xrandr --output HDMI2 --same-as HDMI1
                ;;
        esac
    ;;
esac

#
# Done.
#
