#!/bin/bash
#
# my-minidlna
#

case "$(hostname)" in
    (cheesecake)
        # Always use grep after minidlna status in scripts to ensure
        # that it doesn't block. Use 'grep xyzzy' with text output.
        ok=$(sudo service minidlna status | grep -c 'not accessible')
        case "${ok}" in
            (0)
                sudo service minidlna status | grep -v xyzzy
                ;;
            (1)
                sudo service minidlna stop
                sleep 5s
                sudo service minidlna start
                sleep 2s
                sudo service minidlna status | grep -v xyzzy
                ;;
        esac
        ;;
esac

#
# Done.
#
