#!/bin/bash
#
# my-minidlna
#

case "$(hostname)" in
    (cheesecake)
        # The USB HDD behaves as if it is starved of power despite
        # being the sole device on a powered hub with 2A PSU. This
        # doesn't happen if all other devices and hubs are removed
        # from USB3 and the USB HDD directly connected to USB3.
        #
        # Always use grep after minidlna status in scripts to ensure
        # that it doesn't block. Use 'grep xyzzy' with text output.
        ok=$(sudo service minidlna status | grep -c 'not accessible')
        case "${ok}" in
            (0)
                sudo service minidlna status | grep -v xyzzy
                ;;
            (1)
                sudo service minidlna stop
                sleep 5s
                sudo service minidlna start
                sleep 2s
                sudo service minidlna status | grep -v xyzzy
                ;;
        esac
        ;;
esac

#
# Done.
#
