#!/bin/bash
#
# phonecall
#


# Location of the images to be displayed on dedicated workspaces when
# Tasker detects an incoming phone call. Tasker can detect Skype calls
# and chats,
assets=${HOME}/Pictures
# The xrandr names of the outputs connected to the displays.
lmon=HDMI-2
rmon=HDMI-1

i3-msg "workspace phonecall2,
exec --no-startup-id ristretto -f ${assets}/phonecall2.jpg,
move workspace to output ${rmon};"

sleep 3

i3-msg "workspace phonecall1,
exec --no-startup-id ristretto -f ${assets}/phonecall1.jpg
move workspace to output ${lmon};"

# Pressing Return in Primary mode is bound to code that removes the
# phonecall images from both displays.
i3-msg "mode Primary"

#
# Done.
#
