#!/bin/bash
#
# my-shutdown
#

#
# Gently close apps prior to shutdown.
# - Doing so mitigates the risk of accessing the USB HDDs.
#
apps ()
{
    i3-msg [instance="Navigator"] kill
    i3-msg [instance="emacs"] kill
    i3-msg [instance="urxvt"] kill
    i3-msg [instance="xfce4-terminal"] kill
}

#
# Ensure spindown survives shutdown.
# - This encapsulates the order and timing required.
# - Close the session immediately afterwards.
#
disks ()
{
    my-usb-disks dismount
    sleep 2
    my-usb-disks spindown
}

#
# Start here.
#

eval "$1"

#
# Done.
#
