#!/bin/bash
#
# my-tvheadend
#
# -  tvheadend built from source, running from build directory.
#

tvhpath=/home/shevek/Zebra/packages/tvheadend/tvheadend/build.linux

case "$1" in
    (start)
	(eval urxvt -title 'tvheadend' -e ${tvhpath}/tvheadend --noacl) &
	;;
    (stop)
	pkill -f "urxvt -title 'tvheadend' -e  ${tvhpath}tvheadend --no-acl"
	;;
esac

#
# Done.
#
