#!/bin/bash
#
# my-tvheadend
#
# -  tvheadend built from source, running from build directory.
# -  I've had to hardcode the build directory and the hostname.
#

case "$(hostname)" in
  (quietpc)
  tvhpath=/home/${USER}/Zebra/packages/tvheadend/tvheadend
  cd "${tvhpath}" || exit
  # shellcheck disable=SC2154
  urxvt -title "tvh-server-${hostname}" -e ./build.linux/tvheadend --noacl
  ;;
esac

#
# Done.
#
