#!/bin/bash
#
# Spin down the USB drives attached to my desktop PC, their blue LEDs
# should stay dark. The 1 Tbyte drive Banana automatically spins down,
# 4 Tbyte drive Tabasco drive only spins down when requested.
#

configure ()
{
    sudo  /usr/sbin/hd-idle -i 0 -a sdc -i 1200 -a sdd -i 1200
}

dismount ()
{
    sudo umount  /mnt/usb-Seagate_M3_Portable_NM14ATY5-0:0-part2
    sudo umount  /mnt/usb-Seagate_M3_Portable_BFF77E010D000086-0:0-part1
}

spindown ()
{
    sudo /usr/sbin/hd-idle -t sdc
    sudo /usr/sbin/hd-idle -t sdd
}

shutdown ()
{
    my-usb-disks spindown
    sleep 3
    my-usb-disks dismount
    sleep 3
    my-usb-disks spindown
    sleep 3
    xfce4-session-logout
}

#
# Start here.
#

"$1"

#
# Done.
#
