#!/bin/bash
#
# my-usb-disks
#


#
# 2021-01-28: hd-idle takes sda/sdb/sdc/sdd argument(s) but the syatem
# no longer guarantees how these map to drives.
#
# Replace hardcoded names {sdc,sdd} with global variables of the same
# name but with the modified name as the value.
#
sdc=$(df -h | grep "usb-Seagate_M3_Portable_BFF77E010D000086-0:0-part1" \
          | awk '{print $1}')  # Banana 1T byte.
sdd=$(df -h | grep "usb-Seagate_M3_Portable_NM14ATY5-0:0-part2" \
          | awk '{print $1}')  # Tabasco 4T byte.
sdc=${sdc:5:3}
sdd=${sdd:5:3}

#
# Set auto spindown times.
#
configure ()
{
   sudo  /usr/sbin/hd-idle -i 0 -a "${sdc}" -i 1200 -a "${sdd}" -i 1200
}

#
# Spindown without logout.
#
spindown ()
{
    case "$1" in
        (all)
            sudo /usr/sbin/hd-idle -t "${sdc}"
            sudo /usr/sbin/hd-idle -t "${sdd}"
            ;;
        (tabasco)
            # This is the only command affecting just one drive.
            # Don't bloat this script with non-essentials.
            # Prefer familiar names like 'tabasco'in commands.
            sudo /usr/sbin/hd-idle -t "${sdd}"
            ;;

    esac
}

#
# Perform a tidy exit from i3wm and xubuntu.
#
# It seems that hd-idle must be called soon after umount to ensure
# that the USB disks stay spun down when the PC shuts down.
#
tidyexit()
{
    sudo  /usr/sbin/hd-idle -i 0 -a "${sdc}" -i 1200 -a "${sdd}" -i 1200
    sleep 10
    sudo umount /mnt/usb-Seagate_M3_Portable_BFF77E010D000086-0:0-part1
    sudo umount /mnt/usb-Seagate_M3_Portable_NM14ATY5-0:0-part2
    sudo /usr/sbin/hd-idle -t "${sdc}"
    sudo /usr/sbin/hd-idle -t "${sdd}"
    # The "--halt" option should perform quietpc shutdown without the
    # dialog that appears without it, BUT it also saves the session.
    sleep 30
    xfce4-session-logout
}


#
# Start here.
#

# Do a "belt and braces" check for "safe" script arguments because
# "sudo" and "/etc/sudoers.d" are involved.
case "$1" in
    (configure|dismount)
        "$1"
        ;;
    (spindown|tidyexit)
        "$1" "$2"
        ;;
    (identify)
        echo "Banana sdc -> ${sdc} Tabasco sdd -> ${sdd}"
        ;;
esac

#
# Done.
#
